### ISSUE TITLE
🤠 WANTED: Aragon Vault App Docs 

### ISSUE THREAD

**Issue by burrrata** [1Hive/mvp#13]
100 HONEY reward for any information leading to the location of the Aragon Vault App docs.

More info [here](https://1hive.github.io/mvp/docs/guides/vault)

**Comment by lkngtn** [comment]
This is probably helpful. https://wiki.aragon.org/dev/apps/vault/

**Comment by burrrata** [comment]
Looks like you're going to get the first bounty! lol
