### ISSUE TITLE
WANTED: Fundraising App Code or User Guide

### ISSUE THREAD

**Issue by burrrata** [1Hive/mvp#15]
🍯 100 HONEY reward for any information leading to the location of the Aragon Fundraising App code or user guide

The only place I've seen it is in the [Wiki Dev Docs](https://wiki.aragon.org/dev/apps/fundraising/). It's not in the [User Guides](https://wiki.aragon.org/tutorials/Aragon_User_Guide/) like the other apps. The [GitHub link](https://github.com/aragon/aragon-apps/tree/master/apps/fundraising) in the docs returns a 404. Hmmm 🤔

**Comment by lkngtn** [comment]
Aragon One's fundraising app may have had some example contracts but was never actually released. The wiki documentation doesn't really reflect that. There was some initial discussions on whether it made sense to revisit it for Aragon 0.8 release, but it looks like instead the plan is to support Aragon Black apiary implementation. https://forum.aragon.org/t/aragon-one-product-scope-for-0-8/741
