### ISSUE TITLE
Guides

### ISSUE THREAD

**Issue by burrrata** [1Hive/mvp#17]
The guides help people do stuff. If someone has questions about how they can use a DAO to empower their community, or add a feature to pre-existing DAO, the guides should tell them how to do that. Guides should explain how to do X with Aragon apps. 

Currently we have:
- blockchain basics (meta-mask, etheruem, aragon, etc...)
- cryptoeconomics (concepts people need to combine apps to create positive sum games for their communities)
- multi-sig (because it was just there in the [Aragon user guides](https://wiki.aragon.org/tutorials/Aragon_User_Guide/#23-create-a-multisig-organization))
- democracy (because it was just there in the [Aragon user guides](https://wiki.aragon.org/tutorials/Aragon_User_Guide/#21-create-a-new-democracy-organization))

What else should we add?
What else should or shouldn't be the scope of the Guides section?
Should Guides even be included in the MVP, or would that be better for V2?
- really for an MVP we just need a functioning DAO/website we can use to run 1Hive, then once we're up and running we can use that MVP (as described in the handbook) to drive the creation of content, code, and projects

**Comment by lkngtn** [comment]
> Should Guides even be included in the MVP, or would that be better for V2?

Agree that we don't need these in the initial MVP scope, we can focus specifically on documenting our organization and its process!

**Comment by burrrata** [comment]
Ported to https://github.com/1Hive/website/issues/11
