### ISSUE TITLE
Update Blog Posts 

### ISSUE THREAD

**Issue by burrrata** [1Hive/mvp#18]
I copied a few posts from the current [Medium blog](https://medium.com/hive-commons) to the [website blog](https://1hive.github.io/mvp/blog/) word for word. This includes a lot of outdated links to socials like Gitter, Slack, etc... Seems like it would make more sense to update those posts with our current socials, which is really just [Keybase](https://keybase.io/team/1hive). Is there any other info we want to add to the blog posts or other channels for people to reach out?

**Comment by lkngtn** [comment]
Yeah we should defnitely update those before we "launch", I can also update them on the medium account. As they do still get traffic there.

**Comment by burrrata** [comment]
Ported this over to https://github.com/1Hive/website/issues/6
