### ISSUE TITLE
Docusaurus How-To Docs 🦕

### ISSUE THREAD

**Issue by burrrata** [1Hive/mvp#2]
<br><br><br>

<h1 align="center">Start Here</h1>
<p align="center">
  The comments in this thread will be outdated. Please check the website for the latest and greatest <a href='https://1hive.github.io/mvp/docs/contributing/docs'>Docusaurus How-to Docs</a> and provide feedback on those.
</p>
<p align="center">
  Thanks! 😊  
</p>

<br><br><br>

Documentation will have a section explaining in dead simple terms how community members can add/change content on the website without using needing to use react/javascript. Once the skeleton is setup, anyone should be able to read the docs, fork the website, make changes, and submit a PR.

**Comment by burrrata** [comment]
I created [a walk through of the Docusaurus docs I found most helpful when updating the site](https://exitus.serveo.net/docs/contributing/docs). I've been working with Docusaurus a lot in the past week and also have a basic understanding of HTML/JS/React. I don't if there what things will be difficult/confusing to someone who's only familiar with using Markdown in something like [HackMD](https://hackmd.io). Any help/suggestions/feedback would be greatly appreciated! :)

**Comment by burrrata** [comment]
### Prerequisites 

Developing the website locally requires a few things:
- Git (`sudo apt-get install git` on linux)
- [Node](https://nodejs.org/en/)  
- [Yarn](https://yarnpkg.com/en/)

If these are not enough, you can check out my [Linux Dev Env](https://github.com/burrrata/linux-dev-env) quickstart guide to see what I'm running locally. If you discover a required dependency that is not in the list above, please open an issue or comment here to let me know! :)

### Pulling the master branch

You'll then go to whatever directory you want to work on the project in and run
- `git clone https://github.com/1Hive/mvp.git`

This will pull all the data to your local environment.

### Configuring siteConfig.js

Open `siteConfig.js` and check that the correct stuff is commented/uncommented for local development vs publishing
- https://github.com/1Hive/mvp/blob/master/website/siteConfig.js#L27

### Building Locally 

Go into the `website` directory
- `yarn` (to init stuff)
- `yarn start` 
If `yarn start` is successful it should begin to serve the website locally. This will include something about a hotreload port (ignore that) and deployment at localhost on port 3000. You'll then navigate to localhost:3000 in your browser and should see the site. If not, please open an issue or comment, however I work on a remote VM that I ssh into, so I can try to help, but won't know anything about developing this on a laptop like Macbook or something. 

If everything is working, you can expect changes to the UI or Markdown to hot reload with a refresh of the page. Changes to Javascript related things will require you to disengage `yarn start` using `ctrl C`, then re-engage by running `yarn start` again. This causes Yarn to reload the whole thing ensuring that your JS changes show up.

Hope that helps! :)

**Comment by burrrata** [comment]
If all of this ☝️ looks like a pain in the ass, it is. It's also totally fine to just update docs or blog posts in Markdown, submit an issue or PR saying you did, and on a regular basis someone (atm me) can integrate them into the website to make sure they're published without bugs.

**Comment by lkngtn** [comment]
I'm thinking we may want to have this guide in a contributor guide in the website/mvp repo. 

It feels like it would be a good pattern for every "Project" repo to have a root level file that provides information for new contributors.

**Comment by burrrata** [comment]
Ported to https://github.com/1Hive/website/blob/master/README.md
