### ISSUE TITLE
Add Your Project

### ISSUE THREAD

**Issue by burrrata** [1Hive/mvp#4]
If you'd like to add a project to the Honeycomb, please leave a comment with the following information:
- a link to an image to display,
- a caption of 2-3 words that explain the image,
- an info link you people to go to when they click on the image

**Comment by lkngtn** [comment]
In the `community` branch I've added a section bellow onboarding for community projects. This seems a bit easier to maintain as each project is just a markdown file imo.

**Comment by burrrata** [comment]
Humans are very visual creatures and I think there's a lot of power in having each project be represented via an image on the main site. People can instantly see that and then explore the projects that they're curious about. Maybe those projects could then have a separate Markdown page on the website that explains more about each project (easy to do this without cluttering up the docs sidebar), or the image could link to the projects own website (if they have one)

**Comment by burrrata** [comment]
Ported to https://github.com/1Hive/website/issues/10
