### ISSUE TITLE
Update website URL

### ISSUE THREAD

**Issue by burrrata** [1Hive/mvp#6]
Right now it's https://1hive.github.io/mvp/
It would be great if it was http://1hive.org
@lkngtn Since you own the domain, do you want to [make that happen](https://help.github.com/en/articles/using-a-custom-domain-with-github-pages)?

**Comment by lkngtn** [comment]
Yeah we can definitely connect it to 1hive.org, but want to hold off just a bit so we can do some editing and clean up before going "live" so to speak.

**Comment by burrrata** [comment]
Yeah 100%. That should be the last thing we do before announcing it :)

**Comment by lkngtn** [comment]
btw the current website is hosted using gh-pages in the https://github.com/1Hive/website repo. So I think when we are happy with whats in MVP repo we can move it there and it should just replace the old website.

**Comment by burrrata** [comment]
Are you thinking to add 1hive.org to the GitHub organization so that then every repo in the org could have it's own github page 1hive.org/name-of-repo (that's what I did with my own website and it's awesome and easy to do), or to actually publish the code currently in the mvp repo to the current website and just replace the old content?

**Comment by burrrata** [comment]
1hive.org now reflects the new website :)
