### ISSUE TITLE
Prepare For Mainnet DAO

### ISSUE THREAD

**Issue by burrrata** [1Hive/mvp#9]
The sooner the thing is live the sooner it's real and we can test bounties with real rewards and get people involved (donating time/money/brainpower/etc). I really want to see this thing become a reality. Rather than saying how long it's going to take, let's break it down into all the tangible deliverables we **need** before mainnet. Then we can just work on those and continue making forward progress, and when we're ready we'll know :)

The goal of this Issue is to outline the concrete that need to happen to make the [currently deployed DAO](https://rinkeby.aragon.org/#/0xe520428C232F6Da6f694b121181f907931fD2211) ready for mainnet?

- Current Rinkeby DAO enables all features that the 1Hive handbook outlines 
- Docs section has decent onboarding guides
- A blog post describing what 1Hive is, why we exist, and what we are doing
- Autark deploys TPS to mainnet

Of these ☝️ 3 are completely within our control. @lkngtn sounds like you were talking to the Autark team about mainnet. Any word on the ETA and would our announcement of 1Hive interfere with their "soft launch"?

**Comment by 0xGabi** [comment]
The contracts from TPS needs to be deployed on mainnet and audits needs to be made before that happen.

I think we should keep testing the rinkeby DAO and report any issue to Autark team

**Comment by burrrata** [comment]
Oh... 🤦 TPS isn't shipped to mannet yet... Ahhhhhhhh major buzzkill. I just assumed that it was. My bad....

So... what's the ETA on that? Also, as we develop that are we going to have access to security auditing partners/resources that other Flock teams have access to? (not sure if each team manages that on their own of if it's an ecosystem wide thing)

**Comment by burrrata** [comment]
In the handbook under [Projects and Tasks](https://1hive.github.io/mvp/docs/community/handbook#projects-and-tasks) it does not define HOW one becomes a reviewer. Do we need to create another token for that? If so, how do we do that?

**Comment by lkngtn** [comment]
> In the handbook under Projects and Tasks it does not define HOW one becomes a reviewer. Do we need to create another token for that? If so, how do we do that?

We could create a token to manage reviewers/curators, but I think the simplest way is to assign the related permissions directly to the individuals as they get that permission.

**Comment by lkngtn** [comment]
> Oh... 🤦 TPS isn't shipped to mannet yet... Ahhhhhhhh major buzzkill. I just assumed that it was. My bad.... So... what's the ETA on that?

I've been told that the TPS folks can deploy to mainnet apm when we are ready to switch over. Im not quite comfortable with moving to mainnet yet, as I want to make sure that we are happy with how things are set up on rinkeby and we haven't really gone through the full workflow there yet.

So the status is that we are the gating factor for a mainnet migration.

**Comment by lkngtn** [comment]
> Current Rinkeby DAO enables all features that the 1Hive handbook outlines

Currently the missing functionality is:
- Redemptions
- Payroll (may need to deploy this to apm ourselves as it is not currently published, apparently it is functional though)
- Rewards (not super urgent in my opinion, but it is easy to install)

**Comment by burrrata** [comment]
Ported to https://github.com/1Hive/deployment/issues/3
